const destinations = [
  {
    id: 1,
    name: "Kyoto",
    country: "Japan",
    region: "Asia",
    image: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800&q=80",
    description: "Wander through ancient temples, serene bamboo groves, and traditional tea houses in Japan's cultural heart.",
    keywords: ["temple", "culture", "zen", "cherry blossom", "history", "asia"],
    price: 1899,
    rating: 4.9,
  },
  {
    id: 2,
    name: "Tokyo",
    country: "Japan",
    region: "Asia",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
    description: "Neon-lit streets, world-class cuisine, and a seamless blend of futuristic city life and tradition.",
    keywords: ["city", "food", "culture", "technology", "nightlife", "asia"],
    price: 2099,
    rating: 4.8,
  },
  {
    id: 3,
    name: "Santorini",
    country: "Greece",
    region: "Europe",
    image: "https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800&q=80",
    description: "Iconic white-washed villages perched above the Aegean Sea, with sunsets that paint the sky in gold.",
    keywords: ["beach", "island", "romantic", "mediterranean", "sunset", "europe"],
    price: 2149,
    rating: 4.8,
  },
  {
    id: 4,
    name: "Athens",
    country: "Greece",
    region: "Europe",
    image: "https://images.unsplash.com/photo-1555993539-1732b0258235?w=800&q=80",
    description: "Walk in the footsteps of philosophers among ancient ruins and vibrant modern neighborhoods.",
    keywords: ["history", "ruins", "culture", "mythology", "food", "europe"],
    price: 1599,
    rating: 4.7,
  },
  {
    id: 5,
    name: "Marrakech",
    country: "Morocco",
    region: "Africa",
    image: "https://images.unsplash.com/photo-1518548419970-58e1b06ceb9d?w=800&q=80",
    description: "Lose yourself in vibrant souks, ornate palaces, and the rhythmic pulse of the medina.",
    keywords: ["market", "culture", "desert", "spice", "adventure", "africa"],
    price: 1299,
    rating: 4.7,
  },
  {
    id: 6,
    name: "Patagonia",
    country: "Argentina",
    region: "South America",
    image: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&q=80",
    description: "Towering glaciers, windswept steppes, and dramatic peaks await the adventurous explorer.",
    keywords: ["hiking", "nature", "adventure", "mountains", "wildlife", "south america"],
    price: 2499,
    rating: 4.9,
  },
  {
    id: 7,
    name: "Bali",
    country: "Indonesia",
    region: "Asia",
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80",
    description: "Rice terraces, sacred temples, and warm hospitality in the Island of the Gods.",
    keywords: ["beach", "temple", "wellness", "tropical", "culture", "asia"],
    price: 1599,
    rating: 4.8,
  },
  {
    id: 8,
    name: "Reykjavik",
    country: "Iceland",
    region: "Europe",
    image: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?w=800&q=80",
    description: "Northern lights, geothermal wonders, and otherworldly landscapes at the edge of the Arctic.",
    keywords: ["aurora", "nature", "adventure", "geothermal", "winter", "europe"],
    price: 2299,
    rating: 4.8,
  },
  {
    id: 9,
    name: "Cusco",
    country: "Peru",
    region: "South America",
    image: "https://images.unsplash.com/photo-1526392060635-9d6019884377?w=800&q=80",
    description: "Gateway to Machu Picchu and the living legacy of the Inca civilization.",
    keywords: ["history", "ruins", "mountains", "culture", "adventure", "south america"],
    price: 1799,
    rating: 4.9,
  },
  {
    id: 10,
    name: "Cape Town",
    country: "South Africa",
    region: "Africa",
    image: "https://images.unsplash.com/photo-1580065644526-40d5f1b0bd9f?w=800&q=80",
    description: "Where mountains meet ocean — vineyards, penguins, and vibrant multicultural neighborhoods.",
    keywords: ["beach", "wine", "wildlife", "mountains", "culture", "africa"],
    price: 1699,
    rating: 4.7,
  },
  {
    id: 11,
    name: "Hanoi",
    country: "Vietnam",
    region: "Asia",
    image: "https://images.unsplash.com/photo-1528127269322-539801943592?w=800&q=80",
    description: "Centuries of history blend with buzzing street life and unforgettable cuisine.",
    keywords: ["food", "culture", "history", "street", "asia", "adventure"],
    price: 1199,
    rating: 4.6,
  },
  {
    id: 12,
    name: "Lisbon",
    country: "Portugal",
    region: "Europe",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=800&q=80",
    description: "Colorful tiles, fado music, and hilltop viewpoints overlooking the Tagus River.",
    keywords: ["culture", "food", "history", "coastal", "europe", "romantic"],
    price: 1399,
    rating: 4.7,
  },
  {
    id: 13,
    name: "Queenstown",
    country: "New Zealand",
    region: "Oceania",
    image: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=800&q=80",
    description: "The adventure capital of the world, framed by crystal lakes and snow-capped peaks.",
    keywords: ["adventure", "nature", "hiking", "skiing", "oceania", "mountains"],
    price: 2599,
    rating: 4.9,
  },
  {
    id: 14,
    name: "Petra",
    country: "Jordan",
    region: "Middle East",
    image: "https://images.unsplash.com/photo-1579606032821-4e61652c46dc?w=800&q=80",
    description: "Walk through the rose-red city carved into sandstone cliffs — a wonder of the ancient world.",
    keywords: ["history", "ruins", "desert", "culture", "adventure", "middle east"],
    price: 1499,
    rating: 4.8,
  },
];
